# Generated by Django 3.0.8 on 2020-07-30 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateTimeField(auto_now=True, verbose_name='Data da Publicação')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem_publicacao/')),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_publicacao',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('data_comentario', models.DateTimeField(auto_now=True, verbose_name='Data do Comentário')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pyblog.Publicacao')),
            ],
            options={
                'db_table': 'tbl_comentarios',
            },
        ),
    ]
