# Generated by Django 3.0.8 on 2020-07-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pyblog', '0002_auto_20200730_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='texto',
            new_name='post',
        ),
    ]
