# Generated by Django 3.0.8 on 2020-08-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pyblog', '0003_auto_20200730_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
