# Generated by Django 3.0.8 on 2020-08-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_pyblog', '0004_auto_20200801_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_pyblog.Publicacao'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_post/'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=200)),
                ('organizador', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img_eventos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_eventos',
            },
        ),
    ]
