# Generated by Django 3.0.8 on 2020-08-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pyblog', '0005_auto_20200803_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='imagem',
        ),
    ]
