# Generated by Django 3.0.8 on 2020-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pyblog', '0007_eventos_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_eventos/'),
        ),
    ]
